import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  // Declarations are generated by a separate `tsc --emitDeclarationOnly`
  // pass (see the `build` script) instead of tsup's built-in `dts` option:
  // tsup's bundled rollup-plugin-dts crashes under TypeScript 7 (it calls
  // an internal ts.sys API that no longer exists). Plain tsc has no such
  // problem since it's just using itself.
  dts: false,
  sourcemap: true,
  clean: true,
  target: 'es2019',
});
